# src/main/resources/application.yml
spring:
  application:
    name: resume-screener-backend
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resume_screener}
    username: ${DB_USERNAME:resumeuser}
    password: ${DB_PASSWORD:resumepass123}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update  # Creates/updates tables automatically
    show-sql: true      # Shows SQL queries in console (helpful for learning)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.resumescreener: DEBUG
    org.hibernate.SQL: DEBUG
